### ISSUE TITLE
Develop operator to Enable Code Ready Tool Chain on Openshift clusters

### ISSUE THREAD

**Issue by dipak-pawar** [fabric8-services/toolchain-operator#7]
- [x] Bootstrap operator using Operator-SDK
- [x] Create sa and add self-provisioner role
- [x] Create oauthclient
- [x] Figure out How to get the routing suffix
- [x] Get Cluster URL 
- [x] Use Cluster-client and update cluster info
